import {currentUser,DEMO_EMAIL,passwordHash,seedDemo,session,sameOrigin,type User} from '@/lib/auth';
import {database,getConfig,saveConfig,record} from '@/lib/store';
import {mergeConfig,slotNames} from '@/lib/config';
import {pagePaths} from '@/lib/pages';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
export async function GET(request:Request){try{const user=await currentUser(request);if(new URL(request.url).searchParams.get('view')==='admin'){if(user?.role!=='admin')return json({error:'Administrator sign-in required.'},403);const db=database();const [users,events]=await Promise.all([db.prepare('SELECT id,email,name,role,status,created_at,last_login FROM users ORDER BY created_at DESC LIMIT 500').all(),db.prepare('SELECT a.*,u.email FROM activity a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 500').all()]);return json({user,config:await getConfig(),users:users.results,activity:events.results})}return json({user})}catch(e){console.error(e);return json({error:'The account service is temporarily unavailable. Please try again.'},503)}}
export async function POST(request:Request){try{if(!sameOrigin(request))return json({error:'Invalid request origin.'},403);if(Number(request.headers.get('content-length')||0)>1500000)return json({error:'This request is too large.'},413);const b:any=await request.json();const db=database();
if(b.action==='login'||b.action==='signup'){const email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8||password.length>128)return json({error:'Use a valid email and a password of 8–128 characters.'},400);await seedDemo();
const failures=await db.prepare("SELECT COUNT(*) AS n FROM activity WHERE name='Login failed' AND detail=? AND created_at>?").bind(email,new Date(Date.now()-600000).toISOString()).first<{n:number}>();if((failures?.n||0)>=10)return json({error:'Too many attempts. Try again in ten minutes.'},429);
if(b.action==='signup'){if(email===DEMO_EMAIL)return json({error:'This email is reserved for the demo administrator.'},400);const name=String(b.name||'').trim().slice(0,100);if(!name)return json({error:'Enter your name.'},400);const found=await db.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(found)return json({error:'An account with this email already exists. Please sign in.'},409);await db.prepare("INSERT INTO users(id,email,name,password,role,status,created_at) VALUES(?,?,?,?,'member','active',?)").bind(crypto.randomUUID(),email,name,await passwordHash(password),new Date().toISOString()).run();await record(null,'Signup',email)}
const stored=await db.prepare('SELECT * FROM users WHERE email=?').bind(email).first<User&{password:string}>();if(!stored||stored.status!=='active'||await passwordHash(password,stored.password.split(':')[0])!==stored.password){await record(null,'Login failed',email);return json({error:'Email or password is incorrect, or this account is suspended.'},401)}const {password:discard,...user}=stored;return json({user},200,{'Set-Cookie':await session(user,request)})}
const user=await currentUser(request);
if(b.action==='logout'){if(user){await db.prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id).run();await record(user.id,'Logout',user.email)}return json({ok:true},200,{'Set-Cookie':'fb_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'})}
if(!user)return json({error:'Please sign in.'},401);
if(b.action==='activity'){const allowed=pagePaths();if(!allowed.includes(String(b.path)))return json({error:'Unknown page.'},400);await record(user.id,'Tool completed',String(b.path));return json({ok:true})}
if(user.role!=='admin')return json({error:'Administrator access required.'},403);
if(b.action==='save'){const c=mergeConfig(b.config||{});const url=(v:string)=>{if(!v)return '';const u=new URL(v);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw new Error('Use an HTTPS URL.');return u.href.replace(/\/$/,'')};c.siteUrl=url(c.siteUrl);c.processorUrl=url(c.processorUrl);if(!c.siteUrl)throw new Error('Enter the website URL.');if(c.adClient&&!/^ca-pub-\d{16}$/.test(c.adClient))throw new Error('AdSense publisher ID must be ca-pub- followed by 16 digits.');if(c.measurementId&&!/^G-[A-Z0-9]+$/.test(c.measurementId))throw new Error('Analytics ID must start with G-.');if(c.analyticsEnabled&&!c.measurementId)throw new Error('Add an Analytics ID first.');if(c.verificationFileName&&!/^google[a-zA-Z0-9_-]+(?: \(\d+\))?\.html$/.test(c.verificationFileName))throw new Error('Choose the original Google verification HTML file.');if(c.verificationFileContent.length>12000||c.verificationFileContent&& !/^google-site-verification:\s*google[^<>\r\n]+\.html\s*$/.test(c.verificationFileContent.trim()))throw new Error('This is not a valid Google verification file.');c.socials=c.socials.map(s=>({...s,url:url(s.url)}));c.uploadLimit=Math.min(200,Math.max(5,Number(c.uploadLimit)||100));for(const key of slotNames){const a=c.ads[key];a.sponsorUrl=url(a.sponsorUrl);a.sponsorImage=url(a.sponsorImage);if(a.enabled&&a.mode==='adsense'&&(!c.adClient||!/^\d+$/.test(a.slotId)))throw new Error(key+': add a publisher ID and numeric ad slot ID.');if(a.enabled&&a.mode==='sponsor'&&(!a.sponsorUrl||!a.sponsorName))throw new Error(key+': add sponsor name and URL.')}if(JSON.stringify(c).length>1200000)throw new Error('Settings are too large.');await saveConfig(c);await record(user.id,'Settings saved','Website settings updated');return json({ok:true,config:c})}
if(b.action==='user-status'){if(b.id==='demo-admin'||b.id===user.id)throw new Error('The demo administrator cannot be suspended.');if(!['active','suspended'].includes(b.status))throw new Error('Invalid status.');await db.batch([db.prepare('UPDATE users SET status=? WHERE id=?').bind(b.status,b.id),db.prepare('DELETE FROM sessions WHERE user_id=?').bind(b.id)]);await record(user.id,'Account updated',String(b.id));return json({ok:true})}
if(b.action==='user-delete'){if(b.id==='demo-admin'||b.id===user.id)throw new Error('The demo administrator cannot be deleted.');await db.batch([db.prepare('DELETE FROM sessions WHERE user_id=?').bind(b.id),db.prepare('DELETE FROM activity WHERE user_id=?').bind(b.id),db.prepare('DELETE FROM users WHERE id=?').bind(b.id)]);await record(user.id,'Account deleted',String(b.id));return json({ok:true})}
return json({error:'Unknown action.'},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'The request could not be completed.'},400)}}
