'use client';

import {useEffect,useState}from 'react';
import {tools,toolPath,type Tool}from '@/lib/catalog';
import {SITE}from '@/lib/site';
import {Icon}from './brand';
import type {AdSlot}from '@/lib/config';
export function SearchBox({hero=false}:{hero?:boolean}){return <form action="/tools/" method="get" className={'searchbox '+(hero?'hero-search':'')} role="search"><Icon name="search"/><input name="q" aria-label="Search tools" placeholder={SITE.category==='file'?'Search PDF tools…':SITE.category==='image'?'Search image tools…':'Search video & audio tools…'} autoComplete="off"/><button type="submit" aria-label="Search"><Icon name="arrow" size={21}/></button></form>}
export function MobileNav({links}:{links:[string,string][]}){const close=(e:any)=>{const d=e.currentTarget.closest('details');if(d)d.removeAttribute('open')};return <details className="mobile-nav"><summary aria-label="Open navigation"><Icon name="menu"/></summary><nav>{links.map(([href,label])=><a href={href} key={href} onClick={close}>{label}</a>)}<a href="/guides/" onClick={close}>Guides</a><a href="/help/" onClick={close}>Help</a></nav></details>}
export function ToolCard({tool}:{tool:Tool}){return <a className={'tool-card '+tool.category} href={toolPath(tool)}><span className="tool-icon"><Icon name={tool.icon}/></span><span className="tool-card-copy"><span className="tool-name">{tool.name}</span><span className="tool-description">{tool.description}</span></span><Icon name="external" size={17} className="card-arrow"/></a>}
export function ToolDirectory({initialTools=tools,initialQuery=''}:{initialTools?:Tool[];initialQuery?:string}){const[q,setQ]=useState(initialQuery);const found=initialTools.filter(t=>`${t.name} ${t.description} ${t.group}`.toLowerCase().includes(q.toLowerCase().trim()));return <div className="directory"><div className="directory-controls"><label className="searchbox"><Icon name="search"/><input aria-label="Find a tool" placeholder="Search by tool or format…" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button onClick={()=>setQ('')} type="button" aria-label="Clear search">×</button>}</label></div><p className="results-count" role="status">{found.length} {found.length===1?'tool':'tools'}{q?` matching “${q}”`:''}</p><div className="tools-grid">{found.map(t=><ToolCard tool={t} key={t.slug}/>)}</div>{!found.length&&<div className="empty-panel"><Icon name="search" size={32}/><h3>No matching tools</h3><p>Try a common format or action such as convert, compress, merge or trim.</p><button className="btn secondary" onClick={()=>setQ('')}>Clear search</button></div>}</div>}
const prefKey=`${SITE.key}-preferences`;
function preferences(){try{return JSON.parse(localStorage.getItem(prefKey)||'{}')}catch{return {}}}
export function CookiePreferences(){const[ads,setAds]=useState(false),[analytics,setAnalytics]=useState(false),[saved,setSaved]=useState(false);useEffect(()=>{const p=preferences();setAds(!!p.ads);setAnalytics(!!p.analytics)},[]);return <div className="preference-panel"><label><span><strong>Advertising</strong><small>Allow configured third-party advertising to load.</small></span><input type="checkbox" checked={ads} onChange={e=>setAds(e.target.checked)}/></label><label><span><strong>Analytics</strong><small>Allow anonymous page activity measurement.</small></span><input type="checkbox" checked={analytics} onChange={e=>setAnalytics(e.target.checked)}/></label><button className="btn primary" onClick={()=>{localStorage.setItem(prefKey,JSON.stringify({ads,analytics}));setSaved(true);window.dispatchEvent(new Event('refit-consent'));window.location.reload()}}>Save preferences</button>{saved&&<p className="success-text" role="status">Preferences saved.</p>}</div>}
export function CookieBanner(){const[show,setShow]=useState(false);useEffect(()=>{setShow(localStorage.getItem(prefKey)===null)},[]);if(!show)return null;const save=(all:boolean)=>{localStorage.setItem(prefKey,JSON.stringify({ads:all,analytics:all}));setShow(false);window.dispatchEvent(new Event('refit-consent'))};return <div className="cookie-banner" role="dialog" aria-label="Cookie preferences"><div><strong>Your privacy choices</strong><p>Conversion tools work without optional analytics or ad cookies.</p></div><div><button className="btn secondary" onClick={()=>save(false)}>Essential only</button><button className="btn primary" onClick={()=>save(true)}>Allow optional</button></div></div>}
export function AdContent({slot,client,vertical=false}:{slot:AdSlot;client:string;vertical?:boolean}){const[consent,setConsent]=useState(false);useEffect(()=>{const update=()=>setConsent(!!preferences().ads);update();window.addEventListener('refit-consent',update);return()=>window.removeEventListener('refit-consent',update)},[]);useEffect(()=>{if(slot.mode!=='adsense'||!consent||!client||!slot.slotId)return;let s=document.getElementById('refit-ads');if(!s){s=document.createElement('script');s.id='refit-ads';(s as HTMLScriptElement).async=true;(s as HTMLScriptElement).src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(client)}`;s.setAttribute('crossorigin','anonymous');document.head.appendChild(s);}setTimeout(()=>{try{((window as any).adsbygoogle=(window as any).adsbygoogle||[]).push({})}catch{}},100)},[slot.mode,slot.slotId,consent,client]);if(slot.mode==='sponsor')return <a className="sponsor" href={slot.sponsorUrl} rel="sponsored noopener noreferrer" target="_blank">{slot.sponsorImage&&<img src={slot.sponsorImage} alt=""/>}<strong>{slot.sponsorName||'Sponsor'}</strong><span>Visit sponsor <Icon name="external" size={14}/></span></a>;if(slot.mode==='adsense')return consent&&client&&slot.slotId?<ins className="adsbygoogle" style={{display:'block',minHeight:vertical?600:90}} data-ad-client={client} data-ad-slot={slot.slotId} data-ad-format="auto" data-full-width-responsive="true"/>:<a href="/cookies/" className="ad-consent">Advertising preferences</a>;return <span className="ad-dimensions">{vertical?'160 × 600':'Responsive ad space'}</span>}
export function Analytics({enabled,id}:{enabled:boolean;id:string}){useEffect(()=>{function init(){if(!enabled||!id||!preferences().analytics||document.getElementById('refit-analytics'))return;const w=window as any;w.dataLayer=w.dataLayer||[];w.gtag=function(){w.dataLayer.push(arguments)};w.gtag('js',new Date());w.gtag('config',id,{send_page_view:true,page_location:location.origin+location.pathname});const s=document.createElement('script');s.id='refit-analytics';s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(id)}`;document.head.appendChild(s)}init();window.addEventListener('refit-consent',init);return()=>window.removeEventListener('refit-consent',init)},[enabled,id]);return null}
