'use client';
import {useState,useEffect} from 'react';
import {tools,toolPath,guides,formats,hubs} from '@/lib/catalog';
import {categories,pageData,contentPages,pagePaths} from '@/lib/pages';
import {type Config} from '@/lib/config';
import {Icon} from './brand';
import dynamic from 'next/dynamic';
const Converter=dynamic(()=>import('./converter').then(m=>m.Converter));
const ClipStudio=dynamic(()=>import('./clip-studio'));
import {CookieBanner,CookiePreferences,Analytics,AdContent} from './discovery';
import Login from './login';
const Admin=dynamic(()=>import('./admin'));
export function Brand(){return <a href="/" className="fb-brand" aria-label="Format Blink home"><span className="brand-crop"><img src="/brand-icon.webp" alt=""/></span><span className="fb-brand-name"><strong>Format</strong><span>Blink</span></span></a>}
const categoryArtwork:Record<string,{src:string;alt:string}>={file:{src:'/pdf-tools-hero.webp',alt:'PDF tools'},image:{src:'/image-tools-hero.webp',alt:'Image tools'},video:{src:'/video-tools-hero.webp',alt:'Video tools'},clip:{src:'/clip-tools-hero.webp',alt:'Clip Studio'}};
const fallbackSatellites:Record<string,string[]>={file:['scissors','image','layers','rotate','hash','type'],image:['rotate','resize','file','settings','crop','code'],video:['scissors','crop','music','plus','settings','image'],clip:['scissors','type','music','image','crop','hash']};
const homeCardCopy:Record<string,{description:string;icon:string}>={file:{description:'Merge, split & convert',icon:'file'},image:{description:'Resize, convert & optimize',icon:'image'},video:{description:'Convert, trim & compress',icon:'video'},clip:{description:'Short-form workflow',icon:'scissors'}};
function visualFor(config:Config,key:string){return config.heroVisuals?.[key]||{mainImage:categoryArtwork[key]?.src||'',satellites:fallbackSatellites[key]||[]}}
function AccentTitle({title}:{title:string}){const words=title.trim().split(/\s+/),last=words.pop()||'';return <>{words.join(' ')}{words.length?' ':''}<span className="accent">{last}</span></>}
function HomeVisualStage(){return <div className="home-stage" aria-label="Format Blink workspaces"><svg className="hero-connectors" viewBox="0 0 520 340" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="fbPath" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#19C6FF"/><stop offset="50%" stopColor="#168BFF"/><stop offset="100%" stopColor="#7B4DFF"/></linearGradient></defs><path d="M110 70 C180 40 340 40 410 70" stroke="url(#fbPath)"/><path d="M110 270 C180 300 340 300 410 270" stroke="url(#fbPath)"/><path d="M110 70 C60 140 60 200 110 270" stroke="url(#fbPath)"/><path d="M410 70 C460 140 460 200 410 270" stroke="url(#fbPath)"/>{[[260,42],[260,298],[60,170],[460,170],[110,70],[410,70],[110,270],[410,270]].map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r={i<4?5:4}/>)}</svg>{categories.map(c=>{const meta=homeCardCopy[c.key];return <a href={'/'+c.path} className={'hero-workspace-card hw-'+c.key} key={c.key}><span className="hero-card-art"><Icon name={meta.icon} size={34}/></span><span className="hero-card-copy"><strong>{c.title}</strong><small>{meta.description}</small></span><span className="hero-card-arrow"><Icon name="chevron" size={13}/></span></a>})}</div>}
function WorkspaceOrbit({config,kind,title}:{config:Config;kind:string;title:string}){const v=visualFor(config,kind),icons=(v.satellites?.length?v.satellites:fallbackSatellites[kind]).slice(0,6);return <div className={'workspace-orbit orbit-'+kind}><div className="workspace-main-art">{v.mainImage?<img src={v.mainImage} alt={title}/>:<Icon name={kind==='file'?'file':kind==='clip'?'scissors':kind} size={88}/>}</div>{icons.map((icon,i)=><span className={'orbit-chip chip-'+(i+1)} key={i}><Icon name={icon} size={24}/></span>)}</div>}
function CategoryHero({config,cat,page}:{config:Config;cat:any;page:any}){const clip=cat.key==='clip';return <section className="page-hero-shell"><div className={'category-hero '+cat.key}><div className="category-hero-copy"><span className="hero-eyebrow"><Icon name="check" size={13}/> YOUR {cat.title.toUpperCase()} WORKSPACE</span><h1><AccentTitle title={page.title}/></h1><p>{page.description}</p><div className="category-features">{(clip?['Fast & simple','No watermark','Works in your browser']:['100% browser based','No signup required','Fast & secure']).map((t,i)=><span key={t}><i className={'feature-dot dot-'+i}/>{t}</span>)}</div></div><WorkspaceOrbit config={config} kind={cat.key} title={cat.title}/></div></section>}

export function Ad({id,config}:{id:string;config:Config}){const slot=config.ads[id];return slot?.enabled?<div className="ad-slot"><span className="ad-label">ADVERTISEMENT</span><AdContent slot={slot} client={config.adClient}/></div>:null}
function TextContent({text}:{text:string}){return <div className="reading-content">{text.split('\n\n').map((part,i)=>{const lines=part.split('\n');return <section key={i}>{lines.length>1&&<h2>{lines[0]}</h2>}<p>{lines.length>1?lines.slice(1).join('\n'):part}</p></section>})}</div>}
export default function Site({path,config}:{path:string;config:Config}){const [user,setUser]=useState<any>(null),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[theme,setTheme]=useState<'light'|'dark'>('light');const page=pageData(path,config);const cat=categories.find(c=>'/'+c.path===path),tool=tools.find(t=>path==='/tools/'+t.slug);const isHome=path==='/',isDirectory=isHome||!!cat||path==='/tools'||path==='/popular-tools'||!!hubs[path+'/'];
useEffect(()=>{fetch('/api/manage').then(r=>r.json()).then((d:any)=>setUser(d.user)).catch(()=>{});const q=new URLSearchParams(location.search).get('q');if(q)setQuery(q);const saved=localStorage.getItem('format-blink-theme');const preferred=saved==='dark'||(!saved&&window.matchMedia?.('(prefers-color-scheme: dark)').matches)?'dark':'light';setTheme(preferred);document.documentElement.dataset.theme=preferred},[]);
const toggleTheme=()=>{const next=theme==='dark'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;localStorage.setItem('format-blink-theme',next)};
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'find_format_tools',description:'Search the visible Format Blink tool directory.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({query:q}:{query:string})=>{if(typeof q!=='string'||q.length>100)throw new Error('Use a search of 100 characters or fewer.');if(!isDirectory)throw new Error('Open the tool directory first.');setQuery(q);return {tools:tools.filter(t=>(t.name+' '+t.description).toLowerCase().includes(q.toLowerCase())).map(t=>({name:t.name,url:toolPath(t)}))}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[isDirectory]);
if(path==='/admin')return <Admin initialConfig={config}/>;
const card=(t:typeof tools[number])=><a className={'fb-tool '+t.category} href={toolPath(t)} key={t.slug}><span className="card-top"><span className="tool-icon"><Icon name={t.icon} size={25}/></span>{t.popular&&<span className="popular-label">POPULAR</span>}</span><h3>{pageData('/tools/'+t.slug,config).title}</h3><p>{pageData('/tools/'+t.slug,config).description}</p><span className="card-foot"><span>{t.group}</span><span className="card-go"><Icon name="chevron" size={13}/></span></span></a>;
let selected=tools.filter(t=>(path!=='/popular-tools'||t.popular)&&(cat?t.category===cat.key:true)&&(filter==='all'||t.category===filter)&&(!hubs[path+'/']||hubs[path+'/'].filter(t))&&(t.name+' '+t.description+' '+t.group).toLowerCase().includes(query.toLowerCase()));if(isHome&&!query&&filter==='all')selected=selected.filter(t=>t.popular);
return <><a href="#main" className="skip-link">Skip to content</a><header className="fb-header"><div className="header-inner"><Brand/><nav className={menu?'fb-nav open':'fb-nav'} aria-label="Main navigation"><a className={isHome?'active':''} href="/">Home</a>{categories.map(c=><a key={c.path} className={path.startsWith('/'+c.path)?'active':''} href={'/'+c.path}>{c.title}</a>)}</nav><button className="theme-toggle" onClick={toggleTheme} aria-label={theme==='dark'?'Use light mode':'Use dark mode'} title={theme==='dark'?'Light mode':'Dark mode'}><Icon name={theme==='dark'?'sun':'moon'} size={18}/></button><a className="login-link" href={user?(user.role==='admin'?'/admin':'/account'):'/login'}><Icon name={user?'settings':'lock'} size={17}/><span>{user?'My account':'Log in'}</span></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}><Icon name="menu"/></button></div></header>{config.announcement&&<div className="announcement">{config.announcement}</div>}
<div className="desktop-ad-rail left"><Ad id="DESKTOP_LEFT" config={config}/></div><div className="desktop-ad-rail right"><Ad id="DESKTOP_RIGHT" config={config}/></div><main id="main" className={'fb-main '+(isHome?'home-main':'')}>
{!isHome&&<div className="breadcrumb"><a href="/">Home</a><Icon name="chevron" size={14}/>{tool&&<><a href={'/'+categories.find(c=>c.key===tool.category)?.path}>{categories.find(c=>c.key===tool.category)?.title}</a><Icon name="chevron" size={14}/></>}<span>{page.title}</span></div>}
{isDirectory&&<>
{isHome?<section className="fb-hero home-hero"><div className="home-hero-inner"><div className="home-hero-copy"><div className="hero-tag"><Icon name="check" size={13}/> YOUR EVERYDAY FILE WORKSPACE</div><h1 className="home-hero-heading"><span className="hero-line hero-line-main">Every format.</span><span className="hero-line hero-line-accent">One place.</span></h1><p>{config.pages['/']?.description||config.heroSubtitle}</p><div className="fb-search"><Icon name="search" size={18}/><input aria-label="Search tools" placeholder="What would you like to do with your file?" value={query} onChange={e=>setQuery(e.target.value)}/><span className="hero-search-count"><b>{tools.length+1} tools</b></span></div><div className="hero-note"><span><Icon name="check" size={16}/>Browser-first</span><span><Icon name="check" size={16}/>No signup required</span><span><Icon name="check" size={16}/>Works on every device</span></div></div><HomeVisualStage/></div><div className="category-grid home-category-row">{categories.map(c=><a href={'/'+c.path} className={'category-tile '+c.key} key={c.key}><span className="tool-icon"><Icon name={c.icon} size={22}/></span><div><h2>{c.title}</h2><p>{c.key==='clip'?'Short-form':`${tools.filter(t=>t.category===c.key).length} utilities`}</p></div><Icon name="chevron" size={16}/></a>)}</div></section>:cat?<CategoryHero config={config} cat={cat} page={page}/>:<section className="fb-heading"><span className="section-kicker">THE COMPLETE TOOLBOX</span><h1>{page.title}</h1><p>{page.description}</p></section>}
<Ad id={isHome?'HOME_TOP':'CATEGORY_TOP'} config={config}/>
{path==='/tools'&&<div className="category-grid">{categories.map(c=><a href={'/'+c.path} className={'category-tile '+c.key} key={c.key}><span className="tool-icon"><Icon name={c.icon} size={25}/></span><div><h2>{c.title}</h2><p>{c.key==='clip'?'Long video to short clips':`${tools.filter(t=>t.category===c.key).length} tools for your files`}</p></div><Icon name="chevron" size={17}/></a>)}</div>}
{cat?.key==='clip'?<><div className="clip-feature"><div><span className="section-kicker">FROM LONG FORM TO SHORT FORM</span><h2>Your best moments,<br/>ready for a shorter story.</h2><p>Upload a video or paste a video link, select transcript sections and create clips with captions, text overlays and mobile-friendly framing.</p><a href="/clips/studio" className="btn primary">Open Clip Studio</a></div><div className="clip-steps">{['Upload & transcribe','Select & group clips','Caption, edit & export'].map((t,i)=><div key={t}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{t}</h3><p>{['Start with your source video.','Choose the moments that belong together.','Set the frame, captions and final look.'][i]}</p></div></div>)}</div></div><p className="notice">{config.processorUrl?'Clip Studio sends selected videos to the connected processing service when you start transcription.':'Transcription and rendering will be available when a processing server is connected. You can explore the studio and preview a video now.'}</p></>:<section className="tool-section"><div className="section-head"><div><h2>{isHome&&!query&&filter==='all'?'Popular tools':query?'Search results':cat?'All '+cat.title.toLowerCase():'Browse all tools'}</h2>{isHome&&<p>The most-used tools across PDF, Image, Video and Clip — ready in one click.</p>}</div>{isHome?<div className="filter-tabs">{[['all','All'],['file','PDF'],['image','Image'],['video','Video'],['clip','Clip']].map(([key,label])=><button aria-pressed={filter===key} className={filter===key?'selected':''} onClick={()=>setFilter(key)} key={key}>{label}</button>)}</div>:<label className="compact-search"><Icon name="search" size={17}/><input aria-label="Find a tool" placeholder="Find a tool" value={query} onChange={e=>setQuery(e.target.value)}/></label>}</div><div className="fb-tools-grid">{selected.map(card)}</div>{!selected.length&&<div className="empty-panel"><Icon name="search" size={30}/><h3>No matching tools</h3><p>Try “PDF”, “compress” or another file format.</p><button onClick={()=>{setQuery('');setFilter('all')}} className="btn secondary">Clear search</button></div>}<p className="directory-count">{selected.length} tools{query?' matching your search':''}</p></section>}
<Ad id={isHome?'HOME_MID':'CATEGORY_MID'} config={config}/>
{isHome&&<><div className="process-strip"><div className="process-intro"><h2>A family flow,<br/>for every file.</h2><p>One simple rhythm that works on every tool in the family.</p></div>{[['01','search','Choose your tool','Find the right tool for your file.'],['02','settings','Make it yours','Upload and adjust the settings.'],['03','download','Save your result','Check your file, then download.']].map(([n,icon,t,d])=><div className="process-step" key={n}><span className="process-icon"><Icon name={icon} size={20}/></span><div><b>{n}</b><h3>{t}</h3><p>{d}</p></div></div>)}</div><Ad id="HOME_BOTTOM" config={config}/></>}
</>}
{tool&&<><div className={'fb-heading tool-title '+tool.category}><span className="tool-icon"><Icon name={tool.icon} size={28}/></span><h1>{page.title}</h1><p>{page.description}</p><span className="local-note"><Icon name="shield" size={15}/>Processed on your device · Your original stays unchanged</span></div><Ad id="TOOL_TOP" config={config}/><Converter tool={{...tool,name:page.title,description:page.description}} limits={{file:config.uploadLimit,image:config.uploadLimit,video:Math.min(config.uploadLimit,100)}}/><Ad id="TOOL_MID" config={config}/><div className="tool-help"><section><h2>How to use {page.title}</h2><ol><li>Choose {tool.multiple?'your files':'a supported file'} from your device.</li><li>Review the settings and select Process file.</li><li>Check your result and download it.</li></ol></section><section><h2>Before you start</h2><p>{tool.note||'Keep your original file until you have reviewed the result. Large files may exceed your browser’s available memory.'}</p><p>Accepted formats: {tool.accept||'Image data URL'}. Output: {tool.output.toUpperCase()}.</p></section></div>{page.content&&<TextContent text={page.content}/>}<div className="section-head"><h2>Related tools</h2></div><div className="fb-tools-grid">{tools.filter(t=>t.category===tool.category&&t.slug!==tool.slug).slice(0,4).map(card)}</div><Ad id="TOOL_BOTTOM" config={config}/></>}
{path==='/clips/studio'&&<><div className="fb-heading"><span className="section-kicker">CLIP STUDIO</span><h1>{page.title}</h1><p>{page.description}</p></div>{!config.processorUrl&&<div className="notice">Video preview is ready. Transcription and rendering need a connected processing server.</div>}<ClipStudio processorBase={config.processorUrl}/></>}
{['/login','/signup'].includes(path)&&<Login signup={path==='/signup'} title={page.title} description={page.description}/>}
{path==='/account'&&<section className="account-panel"><h1>{user?`Hello, ${user.name}`:'Your account'}</h1>{user?<><p>{user.email}</p><p>Account status: {user.status}</p><p>Your conversion file contents are not saved to your account.</p><button className="btn secondary" onClick={async()=>{await fetch('/api/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});location.href='/login'}}>Log out</button></>:<a href="/login" className="btn primary">Sign in</a>}</section>}
{contentPages[path.slice(1)]&&<article className="fb-article"><span className="section-kicker">FORMAT BLINK</span><h1>{page.title}</h1><p className="article-lead">{page.description}</p><TextContent text={page.content}/>{path==='/contact'&&<a className="btn primary" href={'mailto:'+config.email}><Icon name="mail" size={18}/>{config.email}</a>}{path==='/cookies'&&<CookiePreferences/>}</article>}
{['/guides','/formats'].includes(path)&&<><div className="fb-heading"><h1>{page.title}</h1><p>{path==='/guides'?'Practical steps for better file results.':'Choose the right format for the job.'}</p></div><div className="resource-grid">{path==='/guides'?guides.map(g=><a className="resource-card" href={'/guides/'+g[0]} key={g[0]}><div><Icon name="book"/><h3>{g[1]}</h3><p>{g[3]}</p></div></a>):Object.entries(formats).map(([key,f])=><a className="resource-card" href={'/formats/'+key} key={key}><div><span className="format-badge">{key.toUpperCase()}</span><h3>{f.name}</h3><p>{f.best}</p></div></a>)}</div></>}
{(path.startsWith('/guides/')||path.startsWith('/formats/')||path.startsWith('/help/'))&&<article className="fb-article"><h1>{page.title}</h1><p className="article-lead">{page.description}</p><TextContent text={page.content}/><a className="btn primary" href={path.startsWith('/guides/')?'/tools/'+guides.find(g=>path.endsWith(g[0]))?.[2]:'/tools'}>Open related tools</a></article>}
{path==='/sitemap'&&<><div className="fb-heading"><h1>{page.title}</h1><p>Every workspace, tool and resource in one place.</p></div><div className="sitemap-links">{pagePaths().filter(p=>!['/login','/signup','/sitemap'].includes(p)).map(p=><a href={p} key={p}>{p==='/'?'Home':pageData(p,config).title}</a>)}</div></>}
{path==='/events'&&<><div className="fb-heading"><h1>{page.title}</h1><p>Updates from Format Blink.</p></div>{config.events.filter(e=>e.enabled).length?<div className="resource-grid">{config.events.filter(e=>e.enabled).map(e=><article className="resource-card" key={e.id}><div><small>{e.date}</small><h2>{e.title}</h2><p>{e.description}</p></div></article>)}</div>:<div className="empty-panel"><h2>No announcements yet</h2><p>New updates will appear here.</p></div>}</>}
{page.content&&!tool&&!contentPages[path.slice(1)]&&!path.startsWith('/guides/')&&!path.startsWith('/formats/')&&!path.startsWith('/help/')&&<TextContent text={page.content}/>}</main><Ad id="FOOTER_AD" config={config}/><footer className="fb-footer"><div className="footer-inner"><div className="footer-brand"><Brand/><p>{config.footerDescription}</p><span className="footer-private"><Icon name="shield" size={17}/>A little less friction. A lot more done.</span><div className="social-links">{config.socials.filter(s=>s.enabled&&s.url).map(s=><a key={s.name} href={s.url} target="_blank" rel="noopener noreferrer">{s.name}</a>)}</div></div><div className="footer-column"><h3>YOUR TOOLBOX</h3>{categories.map(c=><a href={'/'+c.path} key={c.path}>{c.title}</a>)}<a href="/tools">All tools</a></div><div className="footer-column"><h3>RESOURCES</h3><a href="/guides">Guides</a><a href="/formats">Format library</a><a href="/help">Help center</a><a href="/faq">FAQs</a><a href="/events">News & events</a></div><div className="footer-column"><h3>FORMAT BLINK</h3><a href="/about">About us</a><a href="/contact">Contact</a><a href="/advertising">Advertising</a><a href="/privacy">Privacy policy</a><a href="/terms">Terms & conditions</a></div></div><div className="footer-bottom"><span>{config.footerNote||`© ${new Date().getFullYear()} Format Blink. All rights reserved.`}</span><div><a href="/cookies">Cookie preferences</a><a href="/sitemap">Sitemap</a><a href="/admin">Admin</a></div></div></footer><CookieBanner/><Analytics enabled={config.analyticsEnabled} id={config.measurementId}/></>}
