import type {Tool} from './catalog';
import {canvasBlob, decodeImage, pageSelection, registerMediaEngine, type Settings, type Output} from './engines';
import {runVideoTool} from './video-tools';
type Progress = (n:number, message:string)=>void;
const types:Record<string,string>={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',txt:'text/plain',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation'};
export function output(data:Blob|Uint8Array|string,ext:string,name:string,detail?:string):Output{return {blob:data instanceof Blob?data:new Blob([typeof data==='string'?data:Uint8Array.from(data)],{type:types[ext]||'application/octet-stream'}),name:`${name}.${ext}`,detail};}
export function newCanvas(width:number,height:number){if(!Number.isFinite(width)||!Number.isFinite(height)||width<1||height<1||width>16000||height>16000||width*height>25000000)throw new Error('Output must be within 16,000 pixels per side and 25 megapixels.');const c=document.createElement('canvas');c.width=Math.ceil(width);c.height=Math.ceil(height);return c;}
async function remote(t:Tool,file:File,s:Settings,p:Progress,signal:AbortSignal){
  let processor=(s.processorUrl||'http://127.0.0.1:8766').replace(/\/$/,'');
  const base=new URL(processor);if(base.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(base.hostname))throw new Error('The processor must use HTTPS.');
  const requiredCapability=t.slug==='pdf-to-word'?'pdf-word-auto-ocr-v3':t.slug==='pdf-to-excel'?'pdf-excel-auto-ocr-v2':t.slug==='pdf-to-powerpoint'?'pdf-powerpoint-editable-v2':'';
  if(requiredCapability){
    const supports=async(url:string)=>{try{const r=await fetch(url+'/health',{signal:AbortSignal.any([signal,AbortSignal.timeout(10000)]),cache:'no-store'});const h=await r.json();return r.ok&&h.capabilities?.includes(requiredCapability);}catch{return false;}};
    if(!await supports(processor)){
      if(s.processorUrl)throw new Error('Format Blink cloud processor is running an older release. The Modal tools service must be redeployed; users do not need to install anything.');
      throw new Error('The local Format Blink Tools Processor is outdated. Run the latest Tools Processor setup once to update it.');
    }
  }
  const form=new FormData();form.append('file',file);form.append('settings',JSON.stringify({password:s.password,language:t.slug==='pdf-to-word'?'eng+urd+hin':s.language}));
  p(15,s.processorUrl?'Uploading to the connected processing service…':'Processing on your computer…');
  let response:Response;
  try{response=await fetch(`${processor}/api/tools/${t.slug}`,{method:'POST',body:form,signal});}
  catch{throw new Error(s.processorUrl?'Format Blink cloud processor could not be reached. Please retry shortly.':'Format Blink Tools Processor is not running. Start the local processor, then try again.');}
  if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(typeof error?.detail==='string'?error.detail:`Processing service returned ${response.status}. Please retry later.`);}
  const expected=types[t.output];if(expected&&!response.headers.get('content-type')?.includes(expected))throw new Error('The processor returned an unexpected file type.');
  const blob=await response.blob();if(!blob.size)throw new Error('The processor returned an empty file.');
  return [output(blob,t.output,t.slug)];
}
async function imageTool(t:Tool,f:File,s:Settings,p:Progress,signal:AbortSignal){const im=await decodeImage(f,f.name);signal.throwIfAborted();let w=im.naturalWidth,h=im.naturalHeight;if(t.slug==='image-upscaler'){if(![2,4].includes(s.scale))throw new Error('Choose 2× or 4× enlargement.');w*=s.scale;h*=s.scale;}
  const c=newCanvas(w,h),ctx=c.getContext('2d')!;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';if(t.output==='jpg'){ctx.fillStyle='white';ctx.fillRect(0,0,w,h);}if(t.slug==='blur-image'){if(s.blur<1||s.blur>100)throw new Error('Blur must be between 1 and 100 pixels.');ctx.filter=`blur(${s.blur}px)`;}ctx.drawImage(im,0,0,w,h);ctx.filter='none';
  if(['watermark-image','add-text-to-image'].includes(t.slug)){if(!s.text.trim())throw new Error('Enter text first.');if(s.x<0||s.y<0||s.x>=w||s.y>=h||s.fontSize<1||s.fontSize>300)throw new Error('Choose a text position inside the image and a font size from 1 to 300.');ctx.font=`${s.fontSize}px sans-serif`;ctx.textBaseline='top';ctx.fillStyle=s.color;ctx.globalAlpha=t.slug==='watermark-image'?s.opacity:1;ctx.fillText(s.text,s.x,s.y);}
  p(80,'Encoding your image');return[output(await canvasBlob(c,types[t.output],s.quality/100),t.output,t.slug,`${w} × ${h} px`)];
}
export async function loadPdf(file:File){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdf/pdf.worker.min.mjs';const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),cMapUrl:'/vendor/pdf/cmaps/',cMapPacked:true,standardFontDataUrl:'/vendor/pdf/standard_fonts/',wasmUrl:'/vendor/pdf/wasm/'});try{return {task,pdf:await task.promise};}catch(error){await task.destroy();throw error;}}
async function pdfTool(t:Tool,files:File[],s:Settings,p:Progress,signal:AbortSignal){const {PDFDocument,StandardFonts,rgb,PDFTextField,PDFCheckBox,PDFDropdown,PDFOptionList}=await import('pdf-lib');
  if(t.slug==='heic-to-pdf'){const doc=await PDFDocument.create();for(const [i,f]of files.entries()){signal.throwIfAborted();const im=await decodeImage(f,f.name),c=newCanvas(im.naturalWidth,im.naturalHeight);c.getContext('2d')!.drawImage(im,0,0);const pic=await doc.embedPng(await(await canvasBlob(c)).arrayBuffer());const ratio=Math.min(1,14400/pic.width,14400/pic.height);const w=pic.width*ratio,h=pic.height*ratio;doc.addPage([w,h]).drawImage(pic,{x:0,y:0,width:w,height:h});p((i+1)/files.length*90,'Adding photo');}return[output(await doc.save(),'pdf','heic-photos')];}
  if(t.slug==='compress-pdf'){const doc=await PDFDocument.load(await files[0].arrayBuffer());if(doc.getPageCount()>100)throw new Error('Process up to 100 pages at a time.');p(70,'Optimizing PDF objects…');const bytes=await doc.save({useObjectStreams:true,addDefaultPage:false});return[output(bytes,'pdf','compress-pdf','Text, links and vector content preserved')];}
  if(t.slug==='redact-pdf'){const {task,pdf}=await loadPdf(files[0]);try{if(pdf.numPages>100)throw new Error('Process up to 100 pages at a time.');const selected=s.pages.trim()?pageSelection(s.pages,pdf.numPages):Array.from({length:pdf.numPages},(_,i)=>i);const source=await PDFDocument.load(await files[0].arrayBuffer()),doc=await PDFDocument.create();for(let n=1;n<=pdf.numPages;n++){signal.throwIfAborted();if(!selected.includes(n-1)){const[copied]=await doc.copyPages(source,[n-1]);doc.addPage(copied);p(n/pdf.numPages*95,`Keeping page ${n} searchable`);continue;}const page=await pdf.getPage(n),view=page.getViewport({scale:1}),scale=2,vp=page.getViewport({scale}),c=newCanvas(vp.width,vp.height),ctx=c.getContext('2d')!;await page.render({canvas:c,canvasContext:ctx,viewport:vp}).promise;validateRect(s,view.width,view.height);ctx.fillStyle='black';ctx.fillRect(Math.floor(s.x*scale),Math.floor(s.y*scale),Math.ceil(s.width*scale)+1,Math.ceil(s.height*scale)+1);const bytes=await(await canvasBlob(c,'image/png')).arrayBuffer(),image=await doc.embedPng(bytes);doc.addPage([view.width,view.height]).drawImage(image,{x:0,y:0,width:view.width,height:view.height});c.width=c.height=1;p(n/pdf.numPages*95,`Redacting page ${n} of ${pdf.numPages}`);}return[output(await doc.save(),'pdf','redact-pdf',selected.length===pdf.numPages?'Selected pages securely flattened':'Redacted pages flattened; other pages remain searchable')];}finally{await task.destroy();}}
  const doc=await PDFDocument.load(await files[0].arrayBuffer());
  if(t.slug==='fill-pdf-form'){let values:Record<string,unknown>;try{values=JSON.parse(s.formValues);}catch{throw new Error('Form values must be a JSON object.');}if(!values||typeof values!=='object'||Array.isArray(values)||!Object.keys(values).length)throw new Error('Enter at least one form field value.');const form=doc.getForm();for(const [name,value]of Object.entries(values)){const field=form.getField(name);if(field instanceof PDFTextField)field.setText(String(value));else if(field instanceof PDFCheckBox){if(typeof value!=='boolean')throw new Error(`${name} requires true or false.`);value?field.check():field.uncheck();}else if(field instanceof PDFDropdown||field instanceof PDFOptionList)field.select(String(value));else throw new Error(`Field ${name} is not supported.`);}return[output(await doc.save(),'pdf','filled-form')];}
  const pages=s.pages.trim()?pageSelection(s.pages,doc.getPageCount()):doc.getPageIndices();const font=await doc.embedFont(t.slug==='sign-pdf'?StandardFonts.TimesRomanItalic:StandardFonts.Helvetica);const hex=s.color.replace('#','');const color=rgb(parseInt(hex.slice(0,2),16)/255,parseInt(hex.slice(2,4),16)/255,parseInt(hex.slice(4,6),16)/255);
  for(const index of pages){signal.throwIfAborted();const page=doc.getPage(index);if(page.getRotation().angle!==0)throw new Error('For annotation and cropping, first rotate this PDF to 0° or use an unrotated source.');const box=page.getCropBox(),w=box.width,h=box.height;
    if(t.slug==='crop-pdf'){validateRect(s,w,h);page.setCropBox(box.x+s.x,box.y+h-s.y-s.height,s.width,s.height);}
    else if(t.slug==='pdf-editor'&&s.mode!=='text'){validateRect(s,w,h);page.drawRectangle({x:box.x+s.x,y:box.y+h-s.y-s.height,width:s.width,height:s.height,color,opacity:s.mode==='highlight'?0.3:1});}
    else{if(!s.text.trim()||/[^\x20-\x7e\n]/.test(s.text))throw new Error('Enter basic Latin text for this PDF font.');if(s.fontSize<1||s.fontSize>300||s.x<0||s.y<0||s.y+s.fontSize>h||s.x+font.widthOfTextAtSize(s.text,s.fontSize)>w)throw new Error('Text must fit inside the page. Reduce font size or change its position.');page.drawText(s.text,{x:box.x+s.x,y:box.y+h-s.y-s.fontSize,font,size:s.fontSize,color});}
  }return[output(await doc.save(),'pdf',t.slug)];
}
function validateRect(s:Settings,w:number,h:number){if(![s.x,s.y,s.width,s.height].every(Number.isFinite)||s.x<0||s.y<0||s.width<=0||s.height<=0||s.x+s.width>w||s.y+s.height>h)throw new Error(`Rectangle must fit inside ${Math.round(w)} × ${Math.round(h)}. Coordinates start at the top-left.`);}
export async function processAdditional(t:Tool,files:File[],s:Settings,p:Progress,signal:AbortSignal):Promise<Output[]>{if(!files.length)throw new Error('Choose a file first.');if(t.processing==='server')return remote(t,files[0],s,p,signal);if(t.category==='video'||t.slug==='gif-compressor')return runVideoTool(t,files,s,p,signal,registerMediaEngine);return t.category==='image'?imageTool(t,files[0],s,p,signal):pdfTool(t,files,s,p,signal);}
