export const faqs=[
['Are these tools free?','Yes. The published tools require no account, subscription or payment.'],
['Are my files uploaded?','Conversion files are processed in your browser. They are not sent to a file-processing server.'],
['Can I use the tools on my phone?','Yes. The layout is responsive, although very large files still depend on your device memory and browser.'],
['Why did my converted file get larger?','Different formats compress data differently. An already optimized file may not become smaller.'],
['Will conversion improve quality?','Changing formats cannot recreate detail that is missing from the source. Keep your original until you review the result.'],
['Where are my downloaded files?','Your browser saves results, usually in the Downloads folder. The website does not keep a personal file history.']
];
export const content:Record<string,{heading:string;paragraphs:string[]}[]>={
about:[{heading:'Tools with a focused purpose',paragraphs:['This website is built around one practical media category, with focused conversion and editing tools instead of a crowded all-in-one dashboard.','Most processing happens locally in your browser so you can work quickly without creating an account.']}],
privacy:[{heading:'Local file processing',paragraphs:['Files selected for conversion are handled in browser memory by the tool running on your device. They are not intentionally uploaded to the site owner for conversion.','Page requests, configured analytics and advertising can still communicate with hosting or third-party services. Optional integrations are controlled through cookie preferences.']},{heading:'Admin and settings data',paragraphs:['Administrative settings are stored separately from conversion files. The owner panel never receives the contents of files selected inside a converter.']}],
terms:[{heading:'Use the tools responsibly',paragraphs:['Use the website only with files you are allowed to process. Review generated output before submitting, publishing or deleting an original.','The tools are provided for practical convenience and may not support every codec, profile or unusual file variation.']}],
cookies:[{heading:'Optional integrations',paragraphs:['Conversion tools work without optional analytics or advertising cookies. You can allow or decline those integrations on this browser.','Hosting providers may still use essential technical storage required to deliver the site securely.']}],
advertising:[{heading:'Designed for visible, labelled ads',paragraphs:['The layout includes responsive ad placements in the header flow, content, tool pages, footer and desktop side rails. Advertising must not cover conversion controls or downloads.','The owner panel can configure AdSense slots or direct sponsor placements. Sponsor links are labelled and remain separate from tool controls.']}],
'how-processing-works':[{heading:'From selection to download',paragraphs:['Choose a file and your browser reads it into local memory. The selected tool decodes the source, applies the requested settings and creates a new file for download.','PDF, image and media engines are loaded only when the relevant tool needs them.']}],
'privacy-and-local-processing':[{heading:'What stays on your device',paragraphs:['Selected conversion files and generated results are handled in browser memory. Closing or resetting the page discards the active result link.','Optional analytics and ads receive page-level information only when enabled and allowed; conversion file contents are excluded.']}],
'supported-formats':[{heading:'Choose a real supported file',paragraphs:['Each converter lists accepted extensions. Renaming a file extension does not convert the underlying data.','Codec support and browser decoding can vary, particularly for HEIC, AVIF and older video files.']}],
'file-size-and-performance':[{heading:'Large files need more memory',paragraphs:['Decoded images and video frames can use much more memory than the compressed source file. On phones, start with smaller files and close heavy background tabs.','Video conversion is the most demanding workflow and downloads a local WebAssembly media engine on first use.']}],
'browser-compatibility':[{heading:'Use a current browser',paragraphs:['Use a recent Chrome, Edge, Firefox or Safari release with JavaScript, WebAssembly and standard file APIs enabled.','If one browser cannot decode a particular source codec, try exporting the source to a more common format first.']}],
'conversion-errors':[{heading:'Common checks',paragraphs:['Confirm that the selected file really matches a supported format and is not damaged or password-protected.','For memory errors, reduce the file size, page count, video duration or output resolution and try again.']}],
'download-problems':[{heading:'Saving your result',paragraphs:['Wait for the result panel and then use Download. Some mobile browsers open a preview first, where you can use the browser save action.','Download before closing or resetting the page because temporary result links are not stored in an online account.']}]
};
