import type{Tool}from './catalog';
export type Settings={quality:number;width:number;height:number;angle:number;flip:string;pages:string;text:string;start:number;end:number;resolution:number;x:number;y:number;base64:string;interval:number;palette:number};
export type Output={blob:Blob;name:string;detail?:string};
export const defaultSettings:Settings={quality:85,width:1280,height:720,angle:90,flip:'horizontal',pages:'',text:'CONFIDENTIAL',start:0,end:10,resolution:720,x:0,y:0,base64:'',interval:1,palette:256};
const mime:Record<string,string>={jpg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif',ico:'image/x-icon',mp4:'video/mp4',webm:'video/webm',mp3:'audio/mpeg',pdf:'application/pdf',txt:'text/plain;charset=utf-8',zip:'application/zip'};
const stem=(file?:File)=>file?.name.replace(/\.[^.]+$/,'').replace(/[<>:"/\\|?*]/g,'-')||'refit-file';
const result=(data:any,ext:string,name:string,detail?:string):Output=>({blob:data instanceof Blob?data:new Blob([data],{type:mime[ext]||'application/octet-stream'}),name:name+'.'+ext,detail});
export const canvasBlob=(c:HTMLCanvasElement,type='image/png',quality=.85)=>new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Your browser could not create this image.')),type,quality));
export async function decodeImage(file:Blob,name=''):Promise<HTMLImageElement>{let source=file;if(/\.hei[cf]$/i.test(name)||/image\/hei[cf]/.test(file.type)){const {heicTo}=await import('heic-to');source=await heicTo({blob:file,type:'image/png'}) as Blob;}if(/\.svg$/i.test(name)||file.type==='image/svg+xml'){const text=await file.text();const d=new DOMParser().parseFromString(text,'image/svg+xml');if(d.querySelector('parsererror,script,foreignObject')||/<!ENTITY|@import/i.test(text))throw new Error('Use a valid self-contained SVG without scripts or external resources.');for(const el of d.querySelectorAll('*'))for(const a of Array.from(el.attributes)){if(/^on/i.test(a.name)||((a.name==='href'||a.name==='xlink:href')&&!a.value.startsWith('#'))||/url\(\s*['"]?(?!#)/i.test(a.value))throw new Error('This SVG references active or external content. Export a self-contained SVG first.');}source=new Blob([text],{type:'image/svg+xml'});}const url=URL.createObjectURL(source);try{return await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>im.naturalWidth&&im.naturalHeight?resolve(im):reject(new Error('Image dimensions could not be read.'));im.onerror=()=>reject(new Error('This image could not be decoded. Check the format and try a current browser.'));im.src=url;});}finally{URL.revokeObjectURL(url)}}
function canvas(w:number,h:number){if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w*h>25000000||w>16000||h>16000)throw new Error('Use positive dimensions up to 16,000 pixels per side and 25 megapixels in total.');const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
async function zip(items:{name:string;data:Uint8Array}[],name:string){const{zipSync}=await import('fflate');return result(zipSync(Object.fromEntries(items.map(i=>[i.name,i.data])),{level:0}),'zip',name);}
function makeIco(bytes:Uint8Array,size=32){const out=new Uint8Array(22+bytes.length),v=new DataView(out.buffer);v.setUint16(2,1,true);v.setUint16(4,1,true);out[6]=size===256?0:size;out[7]=size===256?0:size;v.setUint16(10,1,true);v.setUint16(12,32,true);v.setUint32(14,bytes.length,true);v.setUint32(18,22,true);out.set(bytes,22);return out;}
async function imageProcess(t:Tool,files:File[],s:Settings,progress:(n:number,msg:string)=>void,signal:AbortSignal){const file=files[0];if(t.slug==='base64-to-image'){const match=s.base64.trim().match(/^data:image\/(png|jpeg|jpg|webp|gif);base64,([A-Za-z0-9+/=\s]+)$/);if(!match)throw new Error('Paste a complete PNG, JPG, WebP or GIF data URL beginning with data:image/.');const raw=atob(match[2].replace(/\s/g,''));if(raw.length>25*1024*1024)throw new Error('Decoded image exceeds 25 MB.');const b=new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:'image/'+match[1]});await decodeImage(b);return [result(b,match[1]==='jpeg'?'jpg':match[1],'decoded-image')];}
if(t.slug==='image-to-base64'){const value=await new Promise<string>((res,rej)=>{const reader=new FileReader();reader.onload=()=>res(String(reader.result));reader.onerror=rej;reader.readAsDataURL(file)});return [result(value,'txt',stem(file)+'-base64')];}
const image=await decodeImage(file,file.name);signal.throwIfAborted();progress(35,'Image decoded');const iw=image.naturalWidth,ih=image.naturalHeight;if(t.slug==='image-dimensions')return [result(`File: ${file.name}\nWidth: ${iw} px\nHeight: ${ih} px\nAspect ratio: ${(iw/ih).toFixed(4)}\nSize: ${file.size} bytes\n`,'txt',stem(file)+'-dimensions',`${iw} × ${ih} px · ${(iw/ih).toFixed(2)} aspect ratio`)];
let w=iw,h=ih;if(t.slug.startsWith('resize-')||t.slug==='crop-image'){w=Number(s.width);h=Number(s.height);}if(t.slug==='rotate-image'&&s.angle%180!==0){w=ih;h=iw;}if(t.slug==='png-to-ico'){w=h=32;}
const c=canvas(w,h),ctx=c.getContext('2d')!;ctx.imageSmoothingQuality='high';if(t.output==='jpg'){ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);}if(t.slug==='rotate-image'){ctx.translate(w/2,h/2);ctx.rotate(s.angle*Math.PI/180);ctx.drawImage(image,-iw/2,-ih/2);}else if(t.slug==='flip-image'){ctx.translate(s.flip==='horizontal'?w:0,s.flip==='vertical'?h:0);ctx.scale(s.flip==='horizontal'?-1:1,s.flip==='vertical'?-1:1);ctx.drawImage(image,0,0);}else if(t.slug==='crop-image'){if(s.x<0||s.y<0||s.x+w>iw||s.y+h>ih)throw new Error(`Crop must fit inside the ${iw} × ${ih} image.`);ctx.drawImage(image,s.x,s.y,w,h,0,0,w,h);}else ctx.drawImage(image,0,0,w,h);
progress(65,'Creating your new file');signal.throwIfAborted();if(t.slug==='favicon-generator'){const items=[];for(const size of [16,32,48,180]){const ico=canvas(size,size),ic=ico.getContext('2d')!;const ratio=Math.min(size/iw,size/ih),dw=iw*ratio,dh=ih*ratio;ic.drawImage(image,(size-dw)/2,(size-dh)/2,dw,dh);const bytes=new Uint8Array(await(await canvasBlob(ico)).arrayBuffer());items.push({name:`icon-${size}.png`,data:bytes});if(size===32)items.push({name:'favicon.ico',data:makeIco(bytes)})}return[await zip(items,'favicons')];}
if(t.slug==='compress-png'){const module=await import('upng-js');const U=(module as any).default||module;const pixels=ctx.getImageData(0,0,w,h);const encoded=U.encode([pixels.data.buffer],w,h,Number(s.palette)||256);return[result(encoded,'png',stem(file)+'-compressed',`${w} × ${h} px · Palette reduced to ${s.palette} colours`)];}
const b=await canvasBlob(c,t.output==='ico'?'image/png':mime[t.output],s.quality/100);if(t.output==='ico')return[result(makeIco(new Uint8Array(await b.arrayBuffer())),'ico',stem(file))];return[result(b,t.output,stem(file)+'-'+(t.slug.startsWith('compress')?'compressed':t.slug.startsWith('resize')?'resized':'renewed'),`${w} × ${h} px`)];}
export function pageSelection(value:string,total:number){if(!value.trim())throw new Error('Enter page numbers, for example 1, 3-5.');const pages:number[]=[];for(const part of value.split(',')){const m=part.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)throw new Error('Use page numbers or ranges, such as 1, 3-5.');const a=Number(m[1]),b=m[2]?Number(m[2]):a;if(a<1||b<a||b>total)throw new Error(`Page ranges must be between 1 and ${total}.`);for(let n=a;n<=b;n++)pages.push(n-1);}if(new Set(pages).size!==pages.length)throw new Error('Each page number should appear only once.');return pages;}
async function pdfProcess(t:Tool,files:File[],s:Settings,progress:(n:number,msg:string)=>void,signal:AbortSignal){const{PDFDocument,degrees,rgb,StandardFonts}=await import('pdf-lib');const name=stem(files[0]);if(t.slug==='pdf-to-jpg'||t.slug==='pdf-to-png'){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdf/pdf.worker.min.mjs';const loadingTask=pdfjs.getDocument({data:new Uint8Array(await files[0].arrayBuffer()),cMapUrl:'/vendor/pdf/cmaps/',cMapPacked:true,standardFontDataUrl:'/vendor/pdf/standard_fonts/',wasmUrl:'/vendor/pdf/wasm/'});const pdf=await loadingTask.promise;try{if(pdf.numPages>100)throw new Error('Export up to 100 pages at a time. Split a longer PDF first.');const items=[];for(let n=1;n<=pdf.numPages;n++){signal.throwIfAborted();const p=await pdf.getPage(n),vp=p.getViewport({scale:1.5}),c=canvas(Math.ceil(vp.width),Math.ceil(vp.height));await p.render({canvas:c,canvasContext:c.getContext('2d')!,viewport:vp}).promise;const b=await canvasBlob(c,mime[t.output],s.quality/100);items.push({name:`${name}-page-${n}.${t.output}`,data:new Uint8Array(await b.arrayBuffer())});progress(n/pdf.numPages*95,`Exporting page ${n} of ${pdf.numPages}`);c.width=c.height=1;}return items.length===1?[result(items[0].data,t.output,name+'-page-1')]:[await zip(items,name+'-pages')];}finally{await loadingTask.destroy()}}
const output=await PDFDocument.create();if(t.slug==='images-to-pdf'||t.slug==='jpg-to-pdf'){for(let i=0;i<files.length;i++){signal.throwIfAborted();const im=await decodeImage(files[i],files[i].name),c=canvas(im.naturalWidth,im.naturalHeight);c.getContext('2d')!.drawImage(im,0,0);const image=await output.embedPng(await(await canvasBlob(c)).arrayBuffer());const scale=Math.min(1,14400/image.width,14400/image.height),w=image.width*scale,h=image.height*scale;output.addPage([w,h]).drawImage(image,{x:0,y:0,width:w,height:h});progress((i+1)/files.length*90,'Adding image '+(i+1));}return[result(await output.save(),'pdf','images-renewed')];}
if(t.slug==='merge-pdf'){if(files.length<2)throw new Error('Choose at least two PDFs to merge.');for(let i=0;i<files.length;i++){signal.throwIfAborted();const doc=await PDFDocument.load(await files[i].arrayBuffer());for(const p of await output.copyPages(doc,doc.getPageIndices()))output.addPage(p);progress((i+1)/files.length*90,`Merging document ${i+1}`)}return[result(await output.save(),'pdf','merged-document')];}
const doc=await PDFDocument.load(await files[0].arrayBuffer());const total=doc.getPageCount();if(!total)throw new Error('This PDF contains no pages.');if(t.slug==='split-pdf'){if(total>200)throw new Error('Split up to 200 pages at a time.');const items=[];for(let i=0;i<total;i++){signal.throwIfAborted();const d=await PDFDocument.create();const[p]=await d.copyPages(doc,[i]);d.addPage(p);items.push({name:`${name}-page-${i+1}.pdf`,data:await d.save()});progress((i+1)/total*95,`Saving page ${i+1}`)}return[await zip(items,name+'-split')];}
if(['extract-pdf-pages','delete-pdf-pages','reorder-pdf-pages'].includes(t.slug)){let idx=pageSelection(s.pages,total);if(t.slug==='delete-pdf-pages')idx=doc.getPageIndices().filter(i=>!idx.includes(i));if(!idx.length)throw new Error('At least one page must remain.');if(t.slug==='reorder-pdf-pages'&&idx.length!==total)throw new Error(`Include all ${total} pages exactly once in the new order.`);for(const p of await output.copyPages(doc,idx))output.addPage(p);return[result(await output.save(),'pdf',name+'-edited')];}
const font=await doc.embedFont(StandardFonts.Helvetica);if(t.slug==='watermark-pdf'&&(!s.text.trim()||/[^\x20-\x7E]/.test(s.text)))throw new Error('Use a watermark of 1–80 basic Latin characters.');for(const[i,p]of doc.getPages().entries()){signal.throwIfAborted();if(t.slug==='rotate-pdf')p.setRotation(degrees((p.getRotation().angle+s.angle)%360));if(t.slug==='add-page-numbers-to-pdf'){const txt=`${i+1} / ${total}`,size=Math.min(11,p.getWidth()/15);p.drawText(txt,{x:Math.max(4,(p.getWidth()-font.widthOfTextAtSize(txt,size))/2),y:Math.min(20,p.getHeight()/15),size,font,color:rgb(.2,.24,.3)})}if(t.slug==='watermark-pdf'){const text=s.text.trim().slice(0,80),size=Math.min(48,p.getWidth()/(text.length*.65));p.drawText(text,{x:p.getWidth()*.08,y:p.getHeight()*.4,size,font,rotate:degrees(30),opacity:.2,color:rgb(.25,.35,.5)})}progress((i+1)/total*90,'Updating pages')}return[result(await doc.save(),'pdf',name+'-edited')];}
let runningFF:any=null;
export function cancelEngine(){if(runningFF){runningFF.terminate();runningFF=null}}
async function videoProcess(t:Tool,files:File[],s:Settings,progress:(n:number,msg:string)=>void,signal:AbortSignal){progress(2,'Loading media engine (about 31 MB on first use)…');const{FFmpeg}=await import('@ffmpeg/ffmpeg');const ff=new FFmpeg();runningFF=ff;let wasmURL='';try{const chunks=await Promise.all([0,1,2,3].map(async n=>{const r=await fetch(`/vendor/ffmpeg-core-${n}.wasm-part`,{signal});if(!r.ok)throw new Error('Media engine could not load. Check your connection and retry.');return await r.arrayBuffer()}));wasmURL=URL.createObjectURL(new Blob(chunks,{type:'application/wasm'}));ff.on('progress',({progress:p}:any)=>progress(Math.max(10,Math.min(94,p*90)),'Processing your media…'));await ff.load({classWorkerURL:location.origin+'/vendor/ffmpeg/worker.js',coreURL:location.origin+'/vendor/ffmpeg-core.js',wasmURL});signal.throwIfAborted();progress(10,'Reading your media');const input='input.'+files[0].name.split('.').pop()!.toLowerCase(),ext=t.output==='zip'?'png':t.output,output=t.output==='zip'?'frame-%04d.png':'output.'+ext;await ff.writeFile(input,new Uint8Array(await files[0].arrayBuffer()));let args=['-threads','1','-filter_threads','1','-filter_complex_threads','1','-i',input];if(t.slug==='trim-video'){if(s.start<0||s.end<=s.start)throw new Error('End time must be greater than start time.');args.push('-ss',String(s.start),'-t',String(s.end-s.start));}
if(ext==='mp3')args.push('-vn','-map','0:a:0','-c:a','libmp3lame','-b:a','192k');else if(ext==='gif')args.push('-t','30','-vf',"fps=10,scale='min(480,iw)':-1:flags=lanczos",'-an','-loop','0');else if(t.output==='zip')args.push('-vf',`fps=1/${Math.max(1,s.interval)}`,'-frames:v','100','-c:v','png','-compression_level','3');else {args.push('-map','0:v:0','-map','0:a:0?');if(t.slug==='resize-video')args.push('-vf',`scale=${Math.max(2,Math.floor(s.width/2)*2)}:-2`);else if(t.slug==='change-video-resolution')args.push('-vf',`scale=-2:${s.resolution}`);else args.push('-vf','scale=trunc(iw/2)*2:trunc(ih/2)*2');if(ext==='webm')args.push('-c:v','libvpx','-b:v','1500k','-crf','10','-deadline','realtime','-cpu-used','8','-c:a','libvorbis','-q:a','4');else args.push('-c:v','libx264','-preset','ultrafast','-crf',t.slug==='compress-video'?String(s.quality>=80?25:s.quality>=55?30:36):'23','-pix_fmt','yuv420p','-c:a','aac','-movflags','+faststart');if(t.slug==='mute-video')args.push('-an');}args.push('-threads','1','-y',output);const code=await ff.exec(args);signal.throwIfAborted();if(code!==0)throw new Error('The media could not be converted. It may use an unsupported codec, have no audio track, or exceed device memory. Try a smaller file.');if(t.output==='zip'){const entries=await ff.listDir('/');const items=[];for(const f of entries.filter((f:any)=>/^frame-\d+\.png$/.test(f.name))){signal.throwIfAborted();const pixels=await ff.readFile(f.name);const im=await decodeImage(new Blob([Uint8Array.from(pixels as Uint8Array)],{type:'image/png'}));const c=canvas(im.naturalWidth,im.naturalHeight);c.getContext('2d')!.drawImage(im,0,0);items.push({name:f.name.replace(/\.png$/,'.jpg'),data:new Uint8Array(await(await canvasBlob(c,'image/jpeg',.9)).arrayBuffer())})}if(!items.length)throw new Error('No video frames could be extracted.');return[await zip(items,stem(files[0])+'-frames')];}const bytes=await ff.readFile(output);if(!bytes.length)throw new Error('The output is empty. Check your trim range and source.');return[result(bytes,ext,stem(files[0])+'-renewed')];}catch(e:any){signal.throwIfAborted();if(/memory|out of bounds/i.test(e.message||String(e)))throw new Error('Your browser could not complete this media conversion. Try a smaller file or a lower resolution.');throw e}finally{if(wasmURL)URL.revokeObjectURL(wasmURL);ff.terminate();if(runningFF===ff)runningFF=null}}
export async function processFiles(t:Tool,files:File[],s:Settings,progress:(n:number,msg:string)=>void,signal:AbortSignal):Promise<Output[]>{signal.throwIfAborted();progress(5,'Preparing your file…');const out=t.category==='image'?await imageProcess(t,files,s,progress,signal):t.category==='file'?await pdfProcess(t,files,s,progress,signal):await videoProcess(t,files,s,progress,signal);signal.throwIfAborted();progress(100,'Ready to download');return out;}
