import type {Tool} from './catalog';
import type {Settings,Output} from './engines';
type Media = {width:number;height:number;duration:number;audio:boolean};
const even=(n:number)=>Math.max(2,Math.floor(n/2)*2);
export function videoArgs(slug:string,s:Settings,m:Media,ext:string):string[]{
  const args=['-i','input'];const filters:string[]=[];let audio='';
  if(slug==='loop-video'){if(!Number.isInteger(s.loops)||s.loops<2||s.loops>10)throw new Error('Choose 2–10 repetitions.');args.unshift('-stream_loop',String(s.loops-1));}
  if(slug==='add-audio-to-video'){args.push('-i','audio','-map','0:v:0','-map','1:a:0','-af','apad','-t',String(m.duration));}
  else if(slug==='add-subtitles-to-video'){args.push('-i','captions.srt','-map','0:v:0','-map','0:a:0?','-map','1:0','-c:s','srt');}
  else args.push('-map','0:v:0','-map','0:a:0?');
  if(slug==='crop-video'){if(![s.x,s.y,s.width,s.height].every(Number.isInteger)||s.width<2||s.height<2||s.x<0||s.y<0||s.x+s.width>m.width||s.y+s.height>m.height)throw new Error(`Crop must fit inside ${m.width} × ${m.height}.`);filters.push(`crop=${even(s.width)}:${even(s.height)}:${s.x}:${s.y}`);}
  if(slug==='rotate-video')filters.push(s.angle===90?'transpose=1':s.angle===270?'transpose=2':'hflip,vflip');
  if(slug==='video-speed-changer'){if(s.speed<0.25||s.speed>4)throw new Error('Speed must be between 0.25× and 4×.');filters.push(`setpts=(PTS-STARTPTS)/${s.speed}`);audio=s.speed<0.5?`atempo=0.5,atempo=${s.speed/0.5}`:s.speed>2?`atempo=2,atempo=${s.speed/2}`:`atempo=${s.speed}`;}
  if(slug==='reverse-video'){if(m.duration>30||m.width*m.height>1920*1080)throw new Error('Reverse supports clips up to 30 seconds at 1080p.');filters.push('reverse');audio='areverse';}
  if(['change-video-aspect-ratio','video-to-9-16'].includes(slug)){const aspect=slug==='video-to-9-16'?'9:16':s.aspect;if(!['16:9','9:16','1:1','4:3'].includes(aspect))throw new Error('Choose a supported aspect ratio.');const [a,b]=aspect.split(':').map(Number),h=720,w=even(h*a/b);filters.push(`scale=${w}:${h}:force_original_aspect_ratio=decrease:force_divisible_by=2,pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2,setsar=1`);}
  filters.push('scale=trunc(iw/2)*2:trunc(ih/2)*2');args.push('-vf',filters.join(','));if(audio&&m.audio)args.push('-af',audio);
  args.push('-c:v',ext==='avi'?'mpeg4':'libx264');if(ext==='avi')args.push('-q:v','5','-c:a','libmp3lame');else args.push('-preset','ultrafast','-crf','23','-pix_fmt','yuv420p','-c:a','aac');
  if(['mp4','mov'].includes(ext))args.push('-movflags','+faststart');return args;
}
export async function runVideoTool(t:Tool,files:File[],s:Settings,p:(n:number,m:string)=>void,signal:AbortSignal,register:(ff:unknown)=>void):Promise<Output[]>{
  const {FFmpeg}=await import('@ffmpeg/ffmpeg');const ff=new FFmpeg();register(ff);let wasm='';const abort=()=>ff.terminate();signal.addEventListener('abort',abort,{once:true});
  const exec=async(args:string[])=>{signal.throwIfAborted();const code=await ff.exec(['-threads','1','-filter_threads','1','-filter_complex_threads','1',...args,'-threads','1','-y']);signal.throwIfAborted();if(code!==0)throw new Error('Media processing failed. Check the input file and settings, or try a shorter clip.');};
  const probe=async(input:string):Promise<Media>=>{await ff.ffprobe(['-v','error','-show_streams','-show_format','-of','json','-o','probe.json',input]);// Some core builds return -1 after a successful ffprobe. Validate the output itself.
let info;try{info=JSON.parse(await ff.readFile('probe.json','utf8') as string);}catch{throw new Error('Could not read media information.');}if(!Array.isArray(info.streams))throw new Error('No media streams were found.');const video=info.streams.find((v:{codec_type:string})=>v.codec_type==='video');if(!video)throw new Error('No video stream found.');const duration=Number(info.format?.duration||video.duration);if(!Number.isFinite(duration)||duration<=0)throw new Error('Video duration could not be read.');return {width:video.width,height:video.height,duration,audio:info.streams.some((v:{codec_type:string})=>v.codec_type==='audio')};};
  try{p(2,'Loading media engine…');const chunks=await Promise.all([0,1,2,3].map(async n=>{const r=await fetch(`/vendor/ffmpeg-core-${n}.wasm-part`,{signal});if(!r.ok)throw new Error('Media engine unavailable. Reload and try again.');return r.arrayBuffer();}));wasm=URL.createObjectURL(new Blob(chunks,{type:'application/wasm'}));ff.on('progress',({progress})=>p(Math.min(94,Math.max(10,progress*90)),'Processing media…'));await ff.load({classWorkerURL:location.origin+'/vendor/ffmpeg/worker.js',coreURL:location.origin+'/vendor/ffmpeg-core.js',wasmURL:wasm});
    if(t.slug==='merge-video'){if(files.length<2)throw new Error('Choose at least two videos.');if(s.width<2||s.height<2||s.width>1920||s.height>1920)throw new Error('Use merge dimensions between 2 and 1920 pixels.');const names=[];for(let i=0;i<files.length;i++){signal.throwIfAborted();await ff.writeFile('input',new Uint8Array(await files[i].arrayBuffer()));const m=await probe('input');const args=['-i','input'];if(!m.audio)args.push('-f','lavfi','-i','anullsrc=r=48000:cl=stereo');args.push('-map','0:v:0','-map',m.audio?'0:a:0':'1:a:0','-vf',`scale=${even(s.width)}:${even(s.height)}:force_original_aspect_ratio=decrease:force_divisible_by=2,pad=${even(s.width)}:${even(s.height)}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=30`,'-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p','-c:a','aac','-ar','48000','-ac','2','-af','apad','-t',String(m.duration),`part-${i}.mp4`);await exec(args);names.push(`file 'part-${i}.mp4'`);p((i+1)/files.length*80,'Normalizing clip '+(i+1));}await ff.writeFile('list.txt',names.join('\n'));await exec(['-f','concat','-safe','0','-i','list.txt','-c','copy','-movflags','+faststart','output.mp4']);}
    else{await ff.writeFile('input',new Uint8Array(await files[0].arrayBuffer()));const media=await probe('input');
      if(t.slug==='gif-compressor'){if(s.width<2||s.width>1600||s.resolution<1||s.resolution>30||![64,128,256].includes(s.palette))throw new Error('Use width 2–1600, frame rate 1–30 and a supported palette.');await exec(['-i','input','-filter_complex',`fps=${s.resolution},scale='min(${s.width},iw)':-1:flags=lanczos,split[a][b];[a]palettegen=max_colors=${s.palette}[pal];[b][pal]paletteuse=dither=bayer`,'-loop','0','output.gif']);}
      else{if(['add-audio-to-video','add-subtitles-to-video'].includes(t.slug)){if(!s.auxiliary)throw new Error(t.slug==='add-audio-to-video'?'Choose a soundtrack file.':'Choose an SRT subtitle file.');if(t.slug==='add-subtitles-to-video'){const text=await s.auxiliary.text();if(!/\d{2}:\d{2}:\d{2}[,.]\d{3}\s*-->/.test(text))throw new Error('Choose a valid SRT file with timestamps.');await ff.writeFile('captions.srt',text);}else await ff.writeFile('audio',new Uint8Array(await s.auxiliary.arrayBuffer()));}await exec([...videoArgs(t.slug,s,media,t.output),'output.'+t.output]);}
    }
    const bytes=await ff.readFile('output.'+t.output);if(typeof bytes==='string'||!bytes.length)throw new Error('The media output is empty.');const types:Record<string,string>={mp4:'video/mp4',mov:'video/quicktime',avi:'video/x-msvideo',mkv:'video/x-matroska',gif:'image/gif'};return[{blob:new Blob([Uint8Array.from(bytes)],{type:types[t.output]}),name:`${t.slug}.${t.output}`}];
  }finally{signal.removeEventListener('abort',abort);ff.terminate();register(null);if(wasm)URL.revokeObjectURL(wasm);}
}
